# Generated by Django 3.1 on 2021-01-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Университет', 'verbose_name_plural': 'Университеты'},
        ),
        migrations.AddField(
            model_name='professor',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
