# Generated by Django 3.1 on 2021-01-17 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professorstory',
            options={'verbose_name': 'История о профессоре', 'verbose_name_plural': 'Истории о профессорах'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.CreateModel(
            name='ProfessorVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField(verbose_name='Вверх?')),
                ('down', models.BooleanField(verbose_name='Вниз?')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос за профессора',
                'verbose_name_plural': 'Голоса за профессоров',
            },
        ),
        migrations.CreateModel(
            name='ProfessorStoryVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField(verbose_name='Вверх?')),
                ('down', models.BooleanField(verbose_name='Вниз?')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professorstory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос за рассказ',
                'verbose_name_plural': 'Голоса за рассказы',
            },
        ),
    ]
