# Generated by Django 3.1 on 2021-01-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_professorstory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professorstoryvote',
            old_name='professor',
            new_name='story',
        ),
    ]
