# Generated by Django 3.1 on 2021-01-20 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_auto_20210119_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorvote',
            name='down',
        ),
        migrations.RemoveField(
            model_name='professorvote',
            name='up',
        ),
        migrations.AddField(
            model_name='professorvote',
            name='vote_int',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)], verbose_name='Голос'),
        ),
    ]
