# Generated by Django 3.1 on 2021-01-20 19:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professors', '0006_auto_20210120_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_int', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)], verbose_name='Голос')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professorstory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос за рассказ',
                'verbose_name_plural': 'Голоса за рассказы',
            },
        ),
        migrations.DeleteModel(
            name='ProfessorStoryVote',
        ),
    ]
