# Generated by Django 3.1 on 2021-01-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_exam_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparesource',
            name='src_type',
            field=models.CharField(choices=[('TXT', 'TEXT'), ('URL', 'URL'), ('DOC', 'DOCUMENT')], default='TXT', max_length=3),
        ),
    ]
